
// This file has been generated by the GUI designer. Do not modify.
namespace lab_5
{
	public partial class PredicatCaculator
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView PredicatSignature;

		private global::Gtk.Label label4;

		private global::Gtk.Entry userInput;

		private global::Gtk.Button calculate;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView resultView;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget lab_5.PredicatCaculator
			this.Name = "lab_5.PredicatCaculator";
			this.Title = global::Mono.Unix.Catalog.GetString("PredicatCaculator");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child lab_5.PredicatCaculator.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.WidthRequest = 900;
			this.fixed3.HeightRequest = 700;
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 880;
			this.GtkScrolledWindow.HeightRequest = 200;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.PredicatSignature = new global::Gtk.TextView();
			this.PredicatSignature.CanFocus = true;
			this.PredicatSignature.Name = "PredicatSignature";
			this.PredicatSignature.Editable = false;
			this.GtkScrolledWindow.Add(this.PredicatSignature);
			this.fixed3.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.GtkScrolledWindow]));
			w2.X = 10;
			w2.Y = 10;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.WidthRequest = 855;
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Інструкція: \n\nДля того аби примінити квантор загальності потрібно ввести символ \"~\" на клавітурі.  Для квантору існування слід ввестисимвол \"#\".  Для того аби додати заперечення використовується символ \"!\". Для введеня декількох виразів в якості символа розділення використовувати \";\"");
			this.label4.Wrap = true;
			this.fixed3.Add(this.label4);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label4]));
			w3.X = 10;
			w3.Y = 220;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.userInput = new global::Gtk.Entry();
			this.userInput.WidthRequest = 790;
			this.userInput.CanFocus = true;
			this.userInput.Name = "userInput";
			this.userInput.Text = global::Mono.Unix.Catalog.GetString("(∃x)(StringPredicat(Str));(∀x)(StringPredicat(Str));(∃x)(¬StringPredicat(Str));(∀x)(¬StringPredicat(Str));");
			this.userInput.IsEditable = true;
			this.userInput.InvisibleChar = '●';
			this.fixed3.Add(this.userInput);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.userInput]));
			w4.X = 10;
			w4.Y = 300;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.calculate = new global::Gtk.Button();
			this.calculate.CanFocus = true;
			this.calculate.Name = "calculate";
			this.calculate.UseUnderline = true;
			this.calculate.Label = global::Mono.Unix.Catalog.GetString("Обчислити");
			this.fixed3.Add(this.calculate);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.calculate]));
			w5.X = 810;
			w5.Y = 297;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.WidthRequest = 880;
			this.GtkScrolledWindow1.HeightRequest = 350;
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.resultView = new global::Gtk.TextView();
			this.resultView.CanFocus = true;
			this.resultView.Name = "resultView";
			this.resultView.Editable = false;
			this.GtkScrolledWindow1.Add(this.resultView);
			this.fixed3.Add(this.GtkScrolledWindow1);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.GtkScrolledWindow1]));
			w7.X = 10;
			w7.Y = 335;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 900;
			this.DefaultHeight = 700;
			this.Show();
		}
	}
}
